services:
  db:
    image: postgres:15-alpine
    container_name: facial_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-facial_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-facial_pass}
      POSTGRES_DB: ${POSTGRES_DB:-facial_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-facial_user}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - facial_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: facial_api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-facial_user}:${POSTGRES_PASSWORD:-facial_pass}@db:5432/${POSTGRES_DB:-facial_db}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER:-facial_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-facial_pass}
      POSTGRES_DB: ${POSTGRES_DB:-facial_db}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM:-${SMTP_USER}}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8501}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      FACE_MATCH_TOLERANCE: ${FACE_MATCH_TOLERANCE:-0.6}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./models:/app/models
      - ./backend:/app/backend
      - /dev:/dev
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - facial_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: facial_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evitar sobreescribir el node_modules del contenedor
    networks:
      - facial_network
    command: npm run dev -- --host 0.0.0.0 --port 8501

  caddy:
    image: docker.io/library/caddy:2-alpine # Proxy inverso para gestionar certificados SSL
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z # Se agrego :z para permitir el acceso al contenedor
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - facial_network
    depends_on:
      - frontend
      - app

volumes:
  postgres_data:
  caddy_data:
  caddy_config:


networks:
  facial_network:
    driver: bridge
